In [18]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [19]:
df = pd.read_csv("../data/cleaned/spam.csv")

# Remove missing values
df = df.dropna(subset=['clean_message'])
df = df[df['clean_message'].str.strip() != ""]

# Convert labels
df['label'] = df['label'].map({
    'ham':0,
    'spam':1
})

df.head()

,label,message,clean_message
0,0,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,0,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts st ...
3,0,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,0,"Nah I don't think he goes to usf, he lives aro...",nah dont think go usf life around though

In [20]:
tfidf = TfidfVectorizer()

X = tfidf.fit_transform(df['clean_message'])

y = df['label']

In [21]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(4452, 7858)
(1114, 7858)

In [22]:
nb = MultinomialNB()

nb.fit(X_train, y_train)

MultinomialNB()

In [23]:
nb_pred = nb.predict(X_test)

In [24]:
print("Accuracy :", accuracy_score(y_test, nb_pred))
print("Precision:", precision_score(y_test, nb_pred))
print("Recall   :", recall_score(y_test, nb_pred))
print("F1 Score :", f1_score(y_test, nb_pred))

Accuracy : 0.9658886894075404
Precision: 1.0
Recall   : 0.7185185185185186
F1 Score : 0.8362068965517241

In [25]:
print(confusion_matrix(y_test, nb_pred))

[[979   0]
 [ 38  97]]

In [26]:
print(classification_report(y_test, nb_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       979
           1       1.00      0.72      0.84       135

    accuracy                           0.97      1114
   macro avg       0.98      0.86      0.91      1114
weighted avg       0.97      0.97      0.96      1114

In [27]:
lr = LogisticRegression(max_iter=1000)

lr.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [28]:
lr_pred = lr.predict(X_test)

In [29]:
print("Accuracy :", accuracy_score(y_test, lr_pred))
print("Precision:", precision_score(y_test, lr_pred))
print("Recall   :", recall_score(y_test, lr_pred))
print("F1 Score :", f1_score(y_test, lr_pred))

Accuracy : 0.9596050269299821
Precision: 0.9787234042553191
Recall   : 0.6814814814814815
F1 Score : 0.8034934497816594

In [30]:
print(confusion_matrix(y_test, lr_pred))

[[977   2]
 [ 43  92]]

In [31]:
print(classification_report(y_test, lr_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98       979
           1       0.98      0.68      0.80       135

    accuracy                           0.96      1114
   macro avg       0.97      0.84      0.89      1114
weighted avg       0.96      0.96      0.96      1114

In [32]:
comparison = pd.DataFrame({
    "Model": ["Naive Bayes", "Logistic Regression"],
    "Accuracy": [
        accuracy_score(y_test, nb_pred),
        accuracy_score(y_test, lr_pred)
    ],
    "Precision": [
        precision_score(y_test, nb_pred),
        precision_score(y_test, lr_pred)
    ],
    "Recall": [
        recall_score(y_test, nb_pred),
        recall_score(y_test, lr_pred)
    ],
    "F1 Score": [
        f1_score(y_test, nb_pred),
        f1_score(y_test, lr_pred)
    ]
})

comparison

                 Model  Accuracy  Precision    Recall  F1 Score
0          Naive Bayes  0.965889   1.000000  0.718519  0.836207
1  Logistic Regression  0.959605   0.978723  0.681481  0.803493

In [33]:
import pandas as pd

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    confusion_matrix,
    classification_report
)

In [34]:
df = pd.read_csv("../data/cleaned/spam.csv")

# Remove missing values
df = df.dropna(subset=['clean_message'])
df = df[df['clean_message'].str.strip() != ""]

# Convert labels to numbers
df['label'] = df['label'].map({'ham': 0, 'spam': 1})

df.head()

,label,message,clean_message
0,0,"Go until jurong point, crazy.. Available only ...",go jurong point crazy available bugis n great ...
1,0,Ok lar... Joking wif u oni...,ok lar joking wif u oni
2,1,Free entry in 2 a wkly comp to win FA Cup fina...,free entry wkly comp win fa cup final tkts st ...
3,0,U dun say so early hor... U c already then say...,u dun say early hor u c already say
4,0,"Nah I don't think he goes to usf, he lives aro...",nah dont think go usf life around though

In [35]:
tfidf = TfidfVectorizer()

X = tfidf.fit_transform(df['clean_message'])

y = df['label']

In [36]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print(X_train.shape)
print(X_test.shape)

(4452, 7858)
(1114, 7858)

In [37]:
nb = MultinomialNB()

nb.fit(X_train, y_train)

MultinomialNB()

In [38]:
nb_pred = nb.predict(X_test)

In [39]:
from sklearn.svm import LinearSVC

In [40]:
svm = LinearSVC(random_state=42)

svm.fit(X_train, y_train)

LinearSVC(random_state=42)

In [41]:
svm_pred = svm.predict(X_test)

In [42]:
print("Accuracy :", accuracy_score(y_test, svm_pred))
print("Precision:", precision_score(y_test, svm_pred))
print("Recall   :", recall_score(y_test, svm_pred))
print("F1 Score :", f1_score(y_test, svm_pred))

Accuracy : 0.9865350089766607
Precision: 0.9918032786885246
Recall   : 0.8962962962962963
F1 Score : 0.9416342412451362

In [43]:
print(confusion_matrix(y_test, svm_pred))

[[978   1]
 [ 14 121]]

In [44]:
print(classification_report(y_test, svm_pred))

              precision    recall  f1-score   support

           0       0.99      1.00      0.99       979
           1       0.99      0.90      0.94       135

    accuracy                           0.99      1114
   macro avg       0.99      0.95      0.97      1114
weighted avg       0.99      0.99      0.99      1114

In [45]:
comparison = pd.DataFrame({
    "Model": ["Naive Bayes", "Logistic Regression", "SVM"],
    "Accuracy": [
        accuracy_score(y_test, nb_pred),
        accuracy_score(y_test, lr_pred),
        accuracy_score(y_test, svm_pred)
    ],
    "Precision": [
        precision_score(y_test, nb_pred),
        precision_score(y_test, lr_pred),
        precision_score(y_test, svm_pred)
    ],
    "Recall": [
        recall_score(y_test, nb_pred),
        recall_score(y_test, lr_pred),
        precision_score(y_test, svm_pred)
    ],
    "F1 Score": [
        f1_score(y_test, nb_pred),
        f1_score(y_test, lr_pred),
        f1_score(y_test, svm_pred)
    ]
})

comparison

                 Model  Accuracy  Precision    Recall  F1 Score
0          Naive Bayes  0.965889   1.000000  0.718519  0.836207
1  Logistic Regression  0.959605   0.978723  0.681481  0.803493
2                  SVM  0.986535   0.991803  0.991803  0.941634